#!/bin/zsh

# Load our prompt settings.

smart_prompt() {

    # Prompt data --------------------------------------------------------------

    user=${$(whoami):l}              # The current user, lowercase

    # Left hand prompt ---------------------------------------------------------

    l_prompt='
$med_grey$user$'                     # User name (preceded by newline)
    l_prompt+='dark_grey@'           # @ separator
    l_prompt+='$med_grey%m '         # Machine name
    l_prompt+='$dark_grey:: '        # :: separator
    l_prompt+='$light_grey%~ '       # Current path
    l_prompt+='$(git_info_prompt)'   # Git information if relevant
    l_prompt+='
$green_1%m '                         # Machine name (preceded by newline)
    l_prompt+='$light_grey%(!.#.>) ' # Prompt (varies if root)
    l_prompt+='$light_grey'          # Reset color to light grey
    
    # Right hand prompt --------------------------------------------------------

    r_prompt='$med_grey%h '          # History line
    r_prompt+='$dark_grey| '         # | separator
    r_prompt+='$med_grey%* '         # Time
    r_prompt+='%D{%f/%m}'            # Date
    r_prompt+='$light_grey'          # Reset color to light grey

    # Set prompts --------------------------------------------------------------

    PROMPT=$l_prompt                 # Set the main (left) prompt
    RPROMPT=$r_prompt                # Set the right prompt
}

# Basic prompt.
dumb_prompt() {
    PS1='$ '
    unsetopt zle
    unsetopt prompt_cr
    unsetopt prompt_subst
    unfunction precmd
    unfunction preexec
}

# Set prompts.
if [[ $TERM == "dumb" ]]; then
    dumb_prompt # Use a super simple prompt for tramp, etc.
else 
    smart_prompt # Use a nice fancy prompt in normal shells.
fi