#!/bin/zsh

if which keychain >/dev/null; then
    # Use keychain to make sure we've got an ssh-agent running.
    keychain --quiet --nocolor ~/.ssh/xyncro
    [[ -f ~/.keychain/$HOST-sh ]] && source ~/.keychain/$HOST-sh
fi
